### ISSUE TITLE
Projectvessel stirbt wenn man zu oft Planeten eradicated

### ISSUE THREAD

**Issue by fxal** [fxal/mse1-fp-projectvessel#29]
Irgendwann ist die Liste ausgeschöpft.

Repl.fs in Zeile 57:
| AtPlanet -> GameText.atPlanet newState.AllPlanets.[string state.CurrPlanet] newState

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Nachricht = The given key was not present in the dictionary.
  Quelle = FSharp.Core
  Stapelüberwachung:
   at Microsoft.FSharp.Collections.MapTreeModule.find[TKey,TValue](IComparer`1 comparer, TKey k, MapTree`2 m) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 155
   at Repl.evaluate(FSharpFunc`2 update, State state, Message msg) in C:\Users\Felix\Documents\workspaces\mse1-fp-projectvessel\src\projectvessel\Repl.fs:line 57
   at Repl.loop[a](State state) in C:\Users\Felix\Documents\workspaces\mse1-fp-projectvessel\src\projectvessel\Repl.fs:line 85
   at Program.main(String[] argv) in C:\Users\Felix\Documents\workspaces\mse1-fp-projectvessel\src\projectvessel\Program.fs:line 13

**Comment by fxal** [comment]
Ich schlage vor Current Planet, All Planet Map umzubauen auf eine ringlist oder so
oder beginn beim ersten wieder
